### ISSUE TITLE
Usage with Heroku?

### ISSUE THREAD

**Issue by ViViDboarder** [robwierzbowski/generator-jekyllrb#113]
I'm new to jekyll, yeoman, and grunt and I'm trying to set up a Jekyll site on Heroku.

I was able to build a simple one from scratch without the generator using the rack/jekyll gem. Is there a way to deploy an application from this generator with grunt instead of using rack/jekyll?

**Comment by dnozay** [comment]
As this is not covered in the yeoman docs (http://yeoman.io/learning/deployment.html) use at your own risk. There may be a `grunt-heroku-deploy` that may be of interest to you.
