### ISSUE TITLE
Installing via Yeoman - where is BrowserSync?

### ISSUE THREAD

**Issue by liquidvisual** [robwierzbowski/generator-jekyllrb#122]
I noticed the contents of the current Grunt file don't match up with what is generated when running

    yo jekyllrb

I've updated the generator. It seems to be stuck on 1.2.1 and with liveReload (not browser sync). Am I missing something?

**Comment by dnozay** [comment]
blame shows it is related to pull request #105

**Comment by dnozay** [comment]
should be in 1.3.0-rc and in 1.4.0

**Comment by dnozay** [comment]
verified with latest release.
