### ISSUE TITLE
Assets not revisioned in dist CSS

### ISSUE THREAD

**Issue by microcosm** [robwierzbowski/generator-jekyllrb#126]
I scaffolded a new instance and started adding background images in the CSS. It works fine on <code>grunt serve</code> but on <code>grunt serve:dist</code> the background images don't load.

Looking at the generated files in <code>dist</code>, I can see that the images are versioned, e.g <code>lab-1-1600.6c4d.jpg</code>, but the CSS isn't:

    #home>header{background:url(/images/lab-1-1600.jpg);

The source CSS looks like this:

    #home>header {
        background: url('/images/lab-1-1600.jpg');
    }

And my Gruntfile:

    filerev: {
      options: {
        length: 4
      },
      dist: {
        files: [{
          src: [
            '<%= yeoman.dist %>/javascript/**/*.js',
            '<%= yeoman.dist %>/stylesheets/**/*.css',
            '<%= yeoman.dist %>/images/**/*.{gif,jpg,jpeg,png,svg,webp}',
            '<%= yeoman.dist %>/fonts/**/*.{eot*,otf,svg,ttf,woff}'
          ]
        }]
      }
    },

Am I missing something?

**Comment by dnozay** [comment]
nothing pointing to `generator-jekyllrb`. when using `grunt-filerev` you need a way to update files with the correct new filename, the rewriting is usually done with `grunt-usemin`.

**Comment by microcosm** [comment]
Ok, I found the problem. This does appear to be a bug.

When <code>generator-jekyllrb</code> generates <code>usemin</code> configuration from setup, it uses the specified <em>source</em> path, not the <em>dist</em> path. In many cases these are the same, but in my case I chose to have verbose naming in the source:

    app/stylesheets/vendor.css
    app/stylesheets/site.css
    
 And squished naming in dist:

    dist/css/style.css

My usemin config was generated like this:

    usemin: {
      ...
      css: ['<%= yeoman.dist %>/stylesheets/**/*.css']
    },

But it should have been generated like this:

    usemin: {
      ...
      css: ['<%= yeoman.dist %>/css/**/*.css']
    },
