### ISSUE TITLE
Gruntfile.js has some double quotes

### ISSUE THREAD

**Issue by gjeck** [robwierzbowski/generator-jekyllrb#128]
The .jshintrc has the following attribute set:``` "quotmark": "single" ```

Causing some warnings upon running grunt commands. There might be a reason for using some double qoutes that I'm not understanding, but if not this should be an easy fix by either removing the double quotes or altering the .jshintrc.

System (Ubuntu 14.04): ```nvm 0.22.1, npm 2.1.18, ruby 2.2.0, bundler 1.7.12```
Example log:
```bash
Running "jshint:all" (jshint) task

Gruntfile.js
  line 54  col 24  Strings must use singlequote.
  line 55  col 21  Strings must use singlequote.
  line 56  col 34  Strings must use singlequote.
  line 65  col 42  Strings must use singlequote.
  line 82  col 24  Strings must use singlequote.
  line 83  col 21  Strings must use singlequote.
  line 84  col 34  Strings must use singlequote.

✖ 7 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by dnozay** [comment]
merged in #129
