### ISSUE TITLE
Request using Gulp and Libsass

### ISSUE THREAD

**Issue by rizqinizamil** [robwierzbowski/generator-jekyllrb#133]
I love this generator, if you don't mind can you create Gulp version and also using Libsass? :)

**Comment by robwierzbowski** [comment]
It is a difficult task. You should give it a shot!

On Monday, February 2, 2015, Rizqi Nizamil Putra <notifications@github.com>
wrote:

> I love this generator, if you don't mind can you create Gulp version and
> also using Libsass? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robwierzbowski/generator-jekyllrb/issues/133>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by dnozay** [comment]
pull requests welcome.

**Comment by dnozay** [comment]
dupe of #116
