### ISSUE TITLE
generator claims to be running `bower install & npm install` but doesn't

### ISSUE THREAD

**Issue by JonathanReeve** [robwierzbowski/generator-jekyllrb#137]
After generating the jekyll app, the generator displays this message: 

    I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

Yet the commands don't seem to be running, and nor do they seem to be exiting, having failed. There is simply nothing that happens after this message is displayed. Running `bower install && npm install` manually seems to work.

**Comment by dnozay** [comment]
maybe https://github.com/yeoman/generator/issues/752

**Comment by dnozay** [comment]
related to https://github.com/yeoman/generator/pull/751
