### ISSUE TITLE
How to make the browser not automatically open on grunt serve

### ISSUE THREAD

**Issue by sondr3** [robwierzbowski/generator-jekyllrb#67]
I have a kind of silly problem. I'm running all my development on a VMware virtual machine (Debian) and every time I run `grunt serve` it open up Iceweasel on the VM, which is both annoying and not needed as I'm viewing it from my host machine. I've looked through the Gruntfile.js but I haven't been able to spot where it automatically makes the browser start. Any way to disable this?

**Comment by DDKnoll** [comment]
Ran into the same problem on most recent build, but browsersync was opening the browser automatically. Had to add `open: false` as an option to browsersync to fix.
