### ISSUE TITLE
Using baseurl, local css file paths and deployed css file names fail

### ISSUE THREAD

**Issue by mashcode** [robwierzbowski/generator-jekyllrb#93]
Hi, 
Using {{ site.baseurl }} prefix for .css files, 'grunt build' doesn't rewrite the /dist/index.html .css file names. I assume grunt build can't rewrite what it can't find. Within this scenario local file paths and remote file names fail.

Is there a jekyll serve --baseurl ' ' equivalent? Gruntfile or .htaccess rewrite method I nay be missing? I could just develop the project in a chosen local branch without baseurl and then push a different gh-pages branch but that would be annoying.

**Comment by aharris88** [comment]
I'm still having this issue. Has this been fixed, or are there instructions on how to use it for github pages project (as opposed to organizations). My github page's css is being generated at `//http://mountainview-webdesign.github.io/lifestonechurch/main.f4ca.css`, but in the index.html it points to `http://mountainview-webdesign.github.io/css/main.f4ca.css`

I can't figure out how to get it to work.
